<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Item_supplier extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Item_supplier_model');
        $this->load->model('Setting_app_model');
        $this->load->library('form_validation');
    }


    function data($item_supplier_id){
        $data=$this->Item_supplier_model->data_list($item_supplier_id);
        echo json_encode($data);
    }

    function hapus(){
        $id=$this->input->post('kode');
        $data=$this->Item_supplier_model->hapus_data($id);
        echo json_encode($data);
    }

    function simpan_data(){
        $item_id_modal= $this->input->post('item_id_modal');
        $update_tgl_modal=$this->input->post('update_tgl_modal');
        $estimasi_harga_supplier_modal=$this->input->post('estimasi_harga_supplier_modal');
        $kd_eksternal_modal=$this->input->post('kd_eksternal_modal');
        $supplier_id_modal=$this->input->post('supplier_id_modal');

        $data=$this->Item_supplier_model->simpan_data($item_id_modal,$supplier_id_modal,$kd_eksternal_modal,$estimasi_harga_supplier_modal,$update_tgl_modal);
        echo json_encode($data);
    }

    function get_data(){
        $id=$this->input->get('id');
        $data=$this->Item_supplier_model->get_data_by_id($id);
        echo json_encode($data);
    }

    function update_data(){
        
        $item_supplier_id = $this->input->post('item_supplier_id_model_edit');
        $arr = array(
            'supplier_id' => $this->input->post('supplier_id_modal_edit'),
            'item_id' => $this->input->post('item_id_modal_edit'),
            'kd_eksternal' => $this->input->post('kd_eksternal_modal_edit'),
            'estimasi_harga_supplier' => $this->input->post('estimasi_harga_supplier_modal_edit'),
            'update_tgl' => $this->input->post('update_tgl_modal_edit'),
        );


        $this->Item_supplier_model->update_data($item_supplier_id, $arr);
        //echo json_encode($arr.'+'.$item_supplier_id);
    }
 
 


    


}

/* End of file Kategori.php */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-22 06:52:35 */
/* http://harviacode.com */
