<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kontak_pelanggan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Kontak_pelanggan_model');
        $this->load->model('Setting_app_model');
        $this->load->library('form_validation');
    }


    function data($pelanggan_id){
        $data=$this->Kontak_pelanggan_model->data_list($pelanggan_id);
        echo json_encode($data);
    }

    function hapus(){
        $id=$this->input->post('kode');
        $data=$this->Kontak_pelanggan_model->hapus_data($id);
        echo json_encode($data);
    }

    function simpan_data(){
        $pelanggan_id= $this->input->post('pelanggan_id');
        $nama=$this->input->post('nama');
        $title_jabatan=$this->input->post('title_jabatan');
        $telepon=$this->input->post('telepon');
        $data=$this->Kontak_pelanggan_model->simpan_data($pelanggan_id,$nama,$title_jabatan,$telepon);
        echo json_encode($data);
    }

    function get_data(){
        $id=$this->input->get('id');
        $data=$this->Kontak_pelanggan_model->get_data_by_id($id);
        echo json_encode($data);
    }

    function update_data(){
        
        $pelanggan_id = $this->input->post('kontak_pelanggan_id2');
        $arr = array(
            'nama' => $this->input->post('nama2'),
            'pelanggan_id' => $this->input->post('pelanggan_id2'),
            'title_jabatan' => $this->input->post('title_jabatan2'),
            'telepon' => $this->input->post('telepon2'),
        );


        $this->Kontak_pelanggan_model->update_data($pelanggan_id, $arr);
        //echo json_encode($arr.'+'.$pelanggan_id);
    }
 
 


    


}

/* End of file Kategori.php */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-22 06:52:35 */
/* http://harviacode.com */
