<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Request_queue extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Request_form_model');
        $this->load->model('Categori_request_model');
        $this->load->model('Setting_app_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        is_allowed($this->uri->segment(1),null);
        $request_form = $this->Request_form_model->get_all_active_request();
        $data = array(
            'request_queue_data' => $request_form,
            'sett_apps' =>$this->Setting_app_model->get_by_id(1),
        );
        $this->template->load('template','request_queue/request_queue_list', $data);
    }

    public function read($id) 
    {
        is_allowed($this->uri->segment(1),'read');
        $row = $this->Request_form_model->get_by_id(decrypt_url($id));
        if ($row) {
            $data = array(
        		'request_form_id' => $row->request_form_id,
                'sett_apps' =>$this->Setting_app_model->get_by_id(1),
        		'kode_request_form' => $row->kode_request_form,
        		'user_id' => $row->user_id,
        		'tanggal_request' => $row->tanggal_request,
        		'categori_request_id' => $row->categori_request_id,
        		'keterangan' => $row->keterangan,
                'whoisreviewing' => $row->approval_status,
                'classnyak' => $this
            );
            $this->template->load('template','request_queue/request_queue_read', $data);
        } else {
            $this->session->set_flashdata('error', 'Record Not Found');
            redirect(site_url('request_queue'));
        }
    }

    function getusername($id)
    {
        $this->load->model('User_m');
        $data = $this->User_m->get_by_id($id);
        return $data;
    }

}

/* End of file Request_form.php */
/* Location: ./application/controllers/Request_form.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-09-14 11:13:12 */
/* http://harviacode.com */