<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Absen_model extends CI_Model
{

    public $table = 'absen';
    public $id = 'absen_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

   	function cek_absensi($id_karyawan, $tanggal)
    {
        $this->db->where('karyawan_id',$id_karyawan);
        $this->db->where('tanggal',$tanggal);
        return $this->db->get('absen')->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function count_terabsen($date)
    {
    	$this->db->where('tanggal', $date);
    	return $this->db->get('absen')->num_rows();
    }


    //still wrking on this shit!

    function recap_monthly($status = '')
    {

        //these query below may affect server's performance, kudu di optimize lagi... "kali"
        $q = $this->db->query("
            SELECT
              karyawan.nama_karyawan,
              SUM(if(month(absen.tanggal) = 1,absen.status = '".$status."',0))  AS 'Januari',
              SUM(if(month(absen.tanggal) = 2,absen.status = '".$status."',0))  AS 'Februari',
              SUM(if(month(absen.tanggal) = 3,absen.status = '".$status."',0))  AS 'Maret',
              SUM(if(month(absen.tanggal) = 4,absen.status = '".$status."',0))  AS 'April',
              SUM(if(month(absen.tanggal) = 5,absen.status = '".$status."',0))  AS 'Mei',
              SUM(if(month(absen.tanggal) = 6,absen.status = '".$status."',0))  AS 'Juni',
              SUM(if(month(absen.tanggal) = 7,absen.status = '".$status."',0))  AS 'Juli',
              SUM(if(month(absen.tanggal) = 8,absen.status = '".$status."',0))  AS 'Agustus',
              SUM(if(month(absen.tanggal) = 9,absen.status = '".$status."',0))  AS 'September',
              SUM(if(month(absen.tanggal) = 10,absen.status = '".$status."',0)) AS 'Oktober',
              SUM(if(month(absen.tanggal) = 11,absen.status = '".$status."',0)) AS 'November',
              SUM(if(month(absen.tanggal) = 12,absen.status = '".$status."',0)) AS 'Desember'
            FROM `absen`
            JOIN karyawan ON karyawan.karyawan_id = absen.karyawan_id
            GROUP BY absen.karyawan_id;
            ");

        return $q->result();
    }
}

/* End of file Categori_benefit_model.php */
/* Location: ./application/models/Categori_benefit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-27 05:13:15 */
/* http://harviacode.com */