<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Absen_model extends CI_Model
{

    public $table = 'absen';
    public $id = 'absen_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

   	function cek_absensi($id_karyawan, $tanggal)
    {
        $this->db->where('karyawan_id',$id_karyawan);
        $this->db->where('tanggal',$tanggal);
        return $this->db->get('absen')->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function count_terabsen($date)
    {
    	$this->db->where('tanggal', $date);
    	return $this->db->get('absen')->num_rows();
    }
}

/* End of file Categori_benefit_model.php */
/* Location: ./application/models/Categori_benefit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-27 05:13:15 */
/* http://harviacode.com */