<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pajak_model extends CI_Model
{

    public $table = 'pajak';
    public $id = 'pajak_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('pajak_id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nilai_tukar', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('akun_pajak_penjualan', $q);
	$this->db->or_like('akun_pajak_pembelian', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pajak_model.php */
/* Location: ./application/models/Pajak_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-09-28 07:03:07 */
/* http://harviacode.com */