<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Spal_model extends CI_Model
{

    public $table = 'spal';
    public $id = 'spal_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('pelanggan', 'pelanggan.pelanggan_id = spal.pelanggan_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('pelanggan', 'pelanggan.pelanggan_id = spal.pelanggan_id', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('spal_id', $q);
	$this->db->or_like('no_spal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('pelanggan_id', $q);
	$this->db->or_like('attn', $q);
	$this->db->or_like('kapal', $q);
	$this->db->or_like('tongkang', $q);
	$this->db->or_like('nama_muatan', $q);
	$this->db->or_like('jumlah_muatan', $q);
	$this->db->or_like('harga_muatan', $q);
	$this->db->or_like('pelabuhan_muat', $q);
	$this->db->or_like('pelabuhan_bongkar', $q);
	$this->db->or_like('metode_pembayaran', $q);
	$this->db->or_like('dokumen', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Spal_model.php */
/* Location: ./application/models/Spal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-06 05:53:23 */
/* http://harviacode.com */