<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Supplier_model extends CI_Model
{

    public $table = 'supplier';
    public $id = 'supplier_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('supplier_id', $q);
	$this->db->or_like('kode_supplier', $q);
	$this->db->or_like('nama_supplier', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('kota', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('personal_kontak', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('halaman_web', $q);
	$this->db->or_like('catatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function buat_kode()   {
        $this->db->select('RIGHT(supplier.kode_supplier,4) as kode', FALSE);
        $this->db->order_by('kode_supplier','DESC');
        // $this->db->where('vessel_id',$vessel_id);    
        $this->db->limit(1);    
        $query = $this->db->get('supplier');      //cek dulu apakah ada sudah ada kode di tabel.    
        if($query->num_rows() <> 0){      
           //jika kode ternyata sudah ada.      
        $data = $query->row();      
        $kode = intval($data->kode) + 1;    
        }
        else {      
           //jika kode belum ada      
        $kode = 1;    
        }
        $kodemax = str_pad($kode, 7, "SPR000", STR_PAD_LEFT); // angka 4 menunjukkan jumlah digit angka 0
        $kodejadi = "".$kodemax;    // hasilnya ODJ-9921-0001 dst.
        return $kodejadi; 
    }

}

/* End of file Supplier_model.php */
/* Location: ./application/models/Supplier_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-09-25 18:14:26 */
/* http://harviacode.com */