<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_sale_model extends CI_Model
{

    public $table = 't_sale';
    public $id = 't_sale_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('t_sale_id', $q);
	$this->db->or_like('invoice', $q);
	$this->db->or_like('pelanggan_id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('attn', $q);
	$this->db->or_like('sub_price', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('final_price', $q);
	$this->db->or_like('note', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function get_cart($params = null){
        $this->db->select('*, item.nama_item as item_name, t_cart.price as cart_price');
        $this->db->from('t_cart');
        $this->db->join('item', 'item.item_id = t_cart.item_id');
        if ($params != null) {
            $this->db->where($params);
        }
        $this->db->where('user_id', $this->session->userdata('userid'));
        $query = $this->db->get();
        return $query;
    }

    public function update_qty($post){
        $sql = "UPDATE t_cart SET price ='$post[estimasi_harga]',
                qty = qty + '$post[qty]',
                total = '$post[estimasi_harga]'*qty where item_id='$post[item_id]'";
        $this->db->query($sql);
    }

    public function add_cart($post){
        // $query = $this->db->query("SELECT MAX(cart_id) as cart_no FROM t_cart");
        // if ($query->num_rows() > 0) {
        //     $row = $query->row();
        //     $cart_no = ((int)$row->cart_no)+1;
        // }else{
        //     $cart_no = "1";
        // }

        $params=array(
            // 'cart_id' =>$cart_no,
            'item_id' =>$post['item_id'],
            'price' =>$post['estimasi_harga'],
            'qty' =>$post['qty'],
            'total' =>($post['estimasi_harga'] * $post['qty']),
            'user_id' =>$this->session->userdata('userid'),

        );
        $this->db->insert('t_cart',$params);
    }

    public function cart_del($params = null){
        if ($params != null) {
            $this->db->where($params);
        }
        $this->db->delete('t_cart');
    }

}

/* End of file T_sale_model.php */
/* Location: ./application/models/T_sale_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-01 06:19:18 */
/* http://harviacode.com */